<article>
    <h1>Správa knih</h1>
    <table>
        <tr>
            <th>Název knihy</th>
            <th>Cena</th>
            <th>URL</th>
            <th>Jméno autora</th>
            <th>Národnost autora</th>
        </tr>
        <?php foreach ($books as $key => $book) : ?>
            <tr>
                <td><?= $book[0] ?></td>
                <td><?= $book[5] ?></td>
                <td><?= $book[1] ?></td>
                <td><?= $book[2] . ' ' . $book[3] ?></td>
                <td><?= $book[4] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <div>
        <h1>Přidání nové knihy</h1>
        <form action="bookManagement" method="post">
            <div>
                <label for="name">Název: </label><input type="text" name="name">
            </div>
            <div><label for="price">Cena: </label><input type="number" min="0" name="price"></div>
            <div><label for="username">Cena: </label><textarea name="password"></textarea></div>
            <input name="login" type="submit" value="login">
        </form>
    </div>
</article>