<article>
    <h1>Správa knih</h1>
    <?php if (isset($successMessage)) : ?>
        <p><?= $successMessage ?></p>
    <?php endif; ?>
    <table>
        <tr>
            <th>Název knihy</th>
            <th>Cena</th>
            <th>URL</th>
            <th>Jméno autora</th>
            <th>Národnost autora</th>
        </tr>
        <?php foreach ($books as $key => $book) : ?>
            <tr>
                <td><?= $book[0] ?></td>
                <td><?= $book[5] ?></td>
                <td><?= $book[1] ?></td>
                <td><?= $book[2] . ' ' . $book[3] ?></td>
                <td><?= $book[4] ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <div>
        <h1>Přidání nové knihy</h1>
        <form action="bookManagement" method="post">
            <div>
                <label for="name">Název: </label><input type="text" name="name">
            </div>
            <div><label for="price">Cena: </label><input type="number" min="0" name="price"></div>
            <div><label for="authorId">Cena: </label>
                <select name="authorId" id="">
                    <?php foreach ($authors as $author) : ?>
                        <option value="<?= $author["author_id"] ?>"><?= $author["name"] . ' ' . $author["surname"] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div><label for="description">Popis: </label><textarea name="description"></textarea></div>
            <input name="addNewBook" type="submit" value="Přidat">
        </form>
    </div>
</article>