<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="/library/">
    <title> <?= $title ?></title>
    <meta name="description" content="<?= $description ?>">
    <meta name="keywords" content="<?= $keyWords ?>">
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <nav><a href="home">Domů</a><a class="login" href="login">Login</a></nav>
    <?php $this->controller->displayView() ?>
    <footer>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo a, harum quod earum reprehenderit neque ipsa obcaecati at id voluptatibus molestias est, quia eos ipsam repellat! Omnis tempore dolorum quae?</p>
    </footer>
</body>

</html>