<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="/library/">
    <title> <?= $title ?></title>
    <meta name="description" content="<?= $description ?>">
    <meta name="keywords" content="<?= $keyWords ?>">
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <?php $this->controller->displayView() ?>
</body>

</html>