<article>
    <h1>Seznam Všech knih</h1>
    <section class="grid">
        <?php foreach ($books as $singleBook) : ?>
            <div>
                <h1><a href="bookDetails/<?= $singleBook[0] ?>"><?= $singleBook[0] ?></a></h1>
                <span>Autor: <?= $singleBook['name'] . ' ' . $singleBook['surname'] ?></span>
                <span>Národnost autora: <?= $singleBook["nationality"] ?></span>
            </div>
        <?php endforeach ?>
    </section>

</article>