<article>
    <form action="login" method="post">
        <div>
            <label for="login">Login: </label><input type="text" name="login"></input>
        </div>
        <div><label for="username">Password: </label><input type="password" name="password"></input></div>
        <input type="submit" value="login">
    </form>
    <span>user: Franta_bezny_uzivatel, pass: xHeslo123</span>
    <span>admin: Admin, pass: xHeslo1234</span>
</article>